### ISSUE TITLE
[REFACTOR] spacedetail, search usecase

### ISSUE THREAD

**Issue by s6m1n** [Indipage/ANDROID#141]
## 화면이름
usecase refectoring

## 작업내용
- [x] SpaceDetailUseCase 추가
- [x] UseCaseModule 수정
- [x] SpaceDetailViewModel 수정
- [x] SearchUseCase 추가
- [x] UseCaseModule 수정
- [x] SearchViewModel 수정

**Comment by lsakee** [comment]
작업내용이 비어있는데욥
